# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0vsGl7PotDIBfJKh2ZIC99t9CZokSQ4
"""

import streamlit as st
import pandas as pd
import plotly.express as px
from gnews import GNews
from textblob import TextBlob
import time

st.set_page_config(page_title="Real-Time News Sentiment", layout="wide")
st.title("📰 Real-Time News Sentiment Dashboard")

news = GNews(language='en')

def fetch_and_classify(limit=20):
    articles = news.get_top_news()[:limit]
    data = []
    for article in articles:
        title = article['title']
        polarity = TextBlob(title).sentiment.polarity
        sentiment = "Positive" if polarity > 0 else "Negative"
        data.append((title, sentiment))
    return pd.DataFrame(data, columns=["headline", "sentiment"])

table_placeholder = st.empty()
chart_placeholder = st.empty()

while True:
    df = fetch_and_classify(20)

    # Show table
    table_placeholder.dataframe(df)

    # Show chart
    fig = px.histogram(df, x="sentiment", title="Sentiment Distribution", color="sentiment")
    chart_placeholder.plotly_chart(fig)

    time.sleep(60)  # refresh every minute
