# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0vsGl7PotDIBfJKh2ZIC99t9CZokSQ4
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import time
from fetch_news import get_labeled_headlines
from spark_model import train_model
from pyspark.sql import SparkSession

st.set_page_config(page_title="Real-Time News Sentiment", layout="wide")
st.title("📰 Real-Time News Sentiment Dashboard")

# Initialize Spark
spark = SparkSession.builder.appName("NewsSentimentApp").getOrCreate()

# Fetch and prepare initial data
headlines = get_labeled_headlines(50)
df = pd.DataFrame(headlines, columns=["headline", "label"])
train_df = spark.createDataFrame(df)

# Train model
model, spark = train_model(train_df)

# Dashboard placeholders
table_placeholder = st.empty()
chart_placeholder = st.empty()

while True:
    new_headlines = get_labeled_headlines(20)
    new_df = pd.DataFrame(new_headlines, columns=["headline", "label"])
    spark_df = spark.createDataFrame(new_df[["headline"]])

    predictions = model.transform(spark_df).toPandas()

    # Show table
    table_placeholder.dataframe(predictions)

    # Plot sentiment distribution
    fig = px.histogram(predictions, x="prediction", title="Real-Time Sentiment Distribution")
    chart_placeholder.plotly_chart(fig)

    time.sleep(60)  # refresh every minute