# -*- coding: utf-8 -*-
"""fetch_news.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DFFBSDMbv_eoVfATqbhEC7OYCl-8kyEM
"""

pip install gnews

from gnews import GNews
from textblob import TextBlob

def get_labeled_headlines(limit=20):
    news = GNews(language='en')
    articles = news.get_top_news()[:limit]
    data = []
    for article in articles:
        title = article['title']
        sentiment = TextBlob(title).sentiment.polarity
        label = 1 if sentiment > 0 else 0
        data.append((title, label))
    return data