# -*- coding: utf-8 -*-
"""spark_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12a58j2NIAsjQpbRMZ_18TwiEfjwWtTNI
"""

from pyspark.sql import SparkSession
from pyspark.ml import Pipeline
from pyspark.ml.feature import Tokenizer, StopWordsRemover, HashingTF, IDF
from pyspark.ml.classification import LogisticRegression

def train_model(df):
    spark = SparkSession.builder.appName("NewsSentimentApp").getOrCreate()

    tokenizer = Tokenizer(inputCol="headline", outputCol="words")
    remover = StopWordsRemover(inputCol="words", outputCol="filtered_words")
    hashingTF = HashingTF(inputCol="filtered_words", outputCol="rawFeatures", numFeatures=1000)
    idf = IDF(inputCol="rawFeatures", outputCol="features")
    lr = LogisticRegression(featuresCol="features", labelCol="label")

    pipeline = Pipeline(stages=[tokenizer, remover, hashingTF, idf, lr])
    model = pipeline.fit(df)
    return model, spark